### ISSUE TITLE
Used transform instead of cv2

### ISSUE THREAD

**Issue by liux2** [Jwrede/neural_style_transfer#1]
In notebook Rescale class, you used `img = transform.resize(image, (new_h, new_w))`, somehow skimage has conflict with numpy. Changing the transform to cv2 fixed the it...

**Comment by Jwrede** [comment]
Hey, thanks alot for the improvement but this is a very old project with many problems, this is also really inefficient for a style transfer model. I think there are much better ways now to do the same thing even in real time (This model takes up to 2 minutes on a cpu) with much better documentation

**Comment by liux2** [comment]
Okay! I will close this issue then.
